### ISSUE TITLE
Global search?

### ISSUE THREAD

**Issue by geckolinux** [classeur/classeur#132] opened 2016-06-21 23:36 UTC
Hello, would it be possible to implement a global search across all documents, similar to this extension for Stackedit? https://github.com/benweet/stackedit/wiki/UserCustom.globalSearch
Thanks!

**Comment by orschiro** [comment] 2016-06-22 05:15
Sensible request, thank you! Labeled as enhancement.

**Comment by benweet** [comment] 2016-06-22 09:49
Duplicate of #39

**Closed as completed by benweet** 2016-06-22 09:49 UTC
Labels: enhancement
