### ISSUE TITLE
Bug: Console Error

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#138] opened 2016-07-15 06:28 UTC
Dear Robert,

I am so sorry to report another bug. Again if this is caused by my mistake, please be so kind to let me know.
# How the bug shows
- I am writing a longer article, standard markdown formatting, nothing special
- At bottom of several lines of text appear, not written by me: "undefined"
- When opening console you see the errors as per snapshot below:

![classeur-console-error](https://cloud.githubusercontent.com/assets/7278716/16865456/7eb62a36-4a97-11e6-9f59-24c8b84b7b06.png)
# Additional Information
- I have several Classeur tabs and windows open
- I am using two screens
- Chrome, latest version
- Win 7, 64 Bit, English
# Is my data safe?

Can you let me know ASAP if I can safely ignore these error messages, or if for the time being it is safe to use another editor until this problem is fixed. So far
# Anything I can do to help you reproduce?

Let me know by writing a comment with your request.

Good hunting,

Hubert

**Comment by VillageHubertChen** [comment] 2016-07-15 06:33
# Update

This bug might be related → #136 . Now I have same symptoms: Scroll-Sync and linking of ToC is broken too :-( 

Any other editor you can recommend me so I can keep working? Stackedit does not allow two open windows at the same time.

**Comment by VillageHubertChen** [comment] 2016-07-15 06:51
# Effort to reproduce the bug

When we copy the text below into a new Classeur Window it will cause the console Error. However, when we tried to strip it down to isolate if any part of the markdown source is tripping the error, we were not successful.

# Introduction

## Purpose of Structured Writing

As authors we are here to serve the reader:
- We strive to inform and educate the reader in a fun and memorable style.
- We structure our articles consistently to make scanning and navigating fast.

## Processes of Structured Writing

This article provides you — the author — processes to deliver quality articles:
- Write clearly by using words the audience understands.
- Compose short and simple sentences.
- Understand the audience and speak directly to the reader.
- Talk to the reader like to your best friend: Use active voice, present tense, and the imperative mood. 
- Remove unnecessary repetition, jargon, and passive voice.
- Lift quality by process of: write, review (ideally via editor), and repeat.
- On important articles write in a team of author, editor, producer, and publisher.
- Use the V² Article Template to provide a familiar and smooth reading flow.

## Where Structured Writing Fits In

In order to provide the reader a wonderful experience the structured writing is but one of 8 processes:

| Article | Purpose |
| --: | :-- |
| [Writing Workflow](https://v-squared.github.io/plan/flow/writing/workflow/) | Creative, effective, quality Writing on Demand |
| [Teamwork](https://v-squared.github.io/plan/flow/writing/teamwork/) | Who is doing what, when, and why. |
| [Structured Writing](https://v-squared.github.io/plan/flow/writing/structured/) | How to write structured, easy to read articles. |
| [Markup Writing](https://v-squared.github.io/plan/flow/writing/markup/) | How to mark up the article's structure. |
| [Appetizing Articles](https://v-squared.github.io/plan/flow/writing/appetizing/) | How to add the extra appeal. |
| [Adding Articles](https://v-squared.github.io/plan/flow/writing/adding-articles/) | How to add articles & groups to V²Site. |
| [Publishing Articles](https://v-squared.github.io/plan/flow/writing/publishing/) | Creating Success by Generating Traffic. |
| [Producing Articles](https://v-squared.github.io/plan/flow/writing/producing/) | Agile Project Management for Articles. |

## But one link in a chain

You all know the saying that a chain is only as strong as its weakest link. Same holds true for structured writing. This analogue delivers you two important understandings:
1. Bad writing is enough to fail an article.
2. Good writing is necessary for the successes, yet not sufficient. All other links in the chain of producing a successful article need to be equally as strong.

## When to apply Markup

### Pro: While Writing

The seasoned author writes the markup while writing the article. In fact this is the magic of markdown, which ironically is the name of the markup language we use. For 

### Beginner: Delegate Markup

# Structure

## Purpose of Structure
- Speed up scanning
- Assist reader in memorizing
- Simplify navigation

## Elements of Structure

### Headings
- Highest Heading Level in Article is Heading 1
- Article Title and Article Sub Title are not expressed via a heading but via _Jumbotron_

## V² Article Template

Note: We only explain purpose and logic of structure here. On how to apply markup to structure read → [Markup Writing](https://v-squared.github.io/plan/flow/writing/markup/).

# II. Grammar, Punctuation, & Capitalization

**Acronyms**: Don’t assume your audience knows what you’re abbreviating. Spell out acronym titles on first reference and follow with the acronym in parenthesis. Every proceeding reference can be abbreviated. Example: The Internet Marketing Association (IMA) is one of the fastest-growing internet marketing groups in the world.

**Ampersand**: Avoid unless part of a proper name, tagline, title, or subheading.

**Apostrophe**: For plural nouns that don’t end in an “s,” add an apostrophe s to the end of the word. For nouns that end in an “s,” add only an apostrophe. Example: several businesses’ websites

Avoid using apostrophes in plurals. Example: URLs, iPhones, FAQs

**Commas**: Observe the Oxford comma. In series of three items or more, keep the comma before and/or. Example: We’ve got to eat these apples, bananas, and oranges. (Not “We’ve got to eat these apples, bananas and oranges.”)

**Company and product names**: Follow an organization’s conventions as to how it capitalizes and punctuates its name, paying special attention to capital letters in the middle of the name and punctuation. Example: eBay, HubSpot, YouTube

**Ellipses**: Use sparingly within copy. 

**Em dash**: Use to set apart entire phrases from the main body of a sentence, and do not separate the dash from the words that precede and follow it. Example: If you want to know—and surely you do—then you must ask.

**Lists**:
- Always capitalize the first word of each bullet point. Just as in regular text, it is important to punctuate lists correctly. 
- If the list is made up of phrases, capitalize the first word of each list item. Do not end each list item with a comma or full-stop (period). 
- When items are complete sentences, begin with a capital and end with a period. 
- List items are sometimes an initial phrase followed by a complete sentence. In that case, use capital letters and full stops (periods) for the phrases as well as the complete sentences. 

**_Keep your lists simple._**
 Examples: 
I love fruit, including:
- Apples
- Oranges
- Bananas

Here’s how you can find the best fruit:
- Go to the grocery store.
- Find the produce section.
- Search for the fruit that’s in season.
- Make sure each piece of fruit you pick out looks delicious.
- Buy the fruit.
- Take the fruit home with you.

**Intel**: Always capitalized. 

**intel.com**: Always lowercase (within a sentence or on its own), unless you’re using it to start a sentence. Example: Intel.com is a great resource. You can find the answer to your question at intel.com.

**Numbers**: Spell out cardinal numbers one through nine, and use numerals for numbers 10 and above. When a number begins a sentence, spell it out. Express large numbers in numerals followed by million, billion, and so forth. If expressing a number greater than 999 in numerals, use a comma. In titles, use numerals. Example: She has nine cats, but he would like 90. One hundred would be too many. So would 5,000. One billion is out of the question.

**OK**: Not o.k. or okay. 

**Percentages**: Always use the % symbol when reporting statistics. Avoid starting a sentence with a percentage. Example: Did you know 98% of statistics are made up?

**Periods**: One space after periods and at the end of sentences.

**Pronouns referring to companies**: When referring to a company, use the third-person singular pronouns it and its. A company is treated as a collective noun and requires a singular verb and a singular pronoun.

**Subheadings**: When using a subheading, capitalize the first letter of every word (like with titles) unless it's in sentence form—then use sentence capitalization and punctuation. If you’re using title capitalization, use an ampersand in place of the word “and.” If you’re using sentence capitalization, spell out “and” as usual.
Examples: 
- Don’t be outsmarted. 
- Do you have enough apples and oranges?
- How To Make The Most Of Your Time
- Exports & Imports
- April, May, & June

**Time**: Use cardinal numbers and a.m. and p.m. to indicate time. Use “noon” to indicate 12 p.m. Example: I was awake at 12 a.m. and 4 a.m., but I fell asleep at my desk at noon.

**Titles**: Capitalize the first letter of every word in titles, and always use an ampersand in place of the word “and.”
Examples: 
- 4 Ways To Make Writing For The Web Less Complicated
- What Is Inbound Marketing & Why Should I Care?

**Commonly Used Words/Acronyms**: 
- all-in-one computer (AiO)
- blog/blog post (The articles we write are called blog posts, not blogs.)
- call-to-action (plural: calls-to-action, abbreviation: CTA or CTAs)
- cell phone
- ebook (“Ebook” when used in a title/headline; avoid using at the beginning of a sentence)
- email/email address (We don’t ask for someone’s email—we ask for their email address.)
- Facebook
- homepage
- internet
- LinkedIn
- tweet
- Twitter
- URL
- website
- white paper

# III. Style & Tone

**Style**

We want our audience to know a V² article or story when they read it. Here are some key components of our copy: 
- Use first person, active voice. Use first-person references like “us,” “we,” and “our team.” 
- Keep it conversational, yet polished. Be polite in your writing, but don’t be afraid to make bold statements.
- Make articles scannable. We include all of the following in our copy: 
  - Short paragraphs
  - Lists
  - Headings
  - Bold and italic
  - Blockquotes
- Parentheticals: We love using them, but limit them to one per paragraph. 
- Keep it simple. The fewer words it takes you to accurately describe something, the better.

**Tone**

 We want our content to have personality. It shouldn’t ever be boring or stagnant. At V², we’re awesome, fun people! And our writing should reflect this. So, enjoy yourself! Keep things informative, but don’t be afraid to be light-hearted. (After all, who wants to read something stuffy?)   Content must be relatable to readers. Therefore, casual, conversational, easy-to-understand copy is a must. We want to consider our audience each time we write to make sure we aren’t using industry-specific jargon they may not understand.   

# IV. Other: Attribution & Social Media

**Attribution**: Always, always give credit to another person’s idea (in whole or in part). Link to the original source, if possible. When referencing online articles in your work, always add a link to the source website spanning a phrase that you’ve written. If you use the title of the article, no italics or quotation marks are necessary. Never cite an article using the word “source.” Make sure all external links open in a new browser tab. Internal links should open within the same browser window.

**Social media**: We’ll play by the “rules” in this style guide on social media, too. Keep your posts respectful, polished, and conversational, and always edit for content and grammar. Social media moves fast, but how we represent our brand and our clients will stick around for a long time. On Twitter, use your best judgment to fit the character count; for example, symbols instead of spelled-out words are OK. 

# Reference

## Special Thanks

Special thanks to: 
- Wikipedia Style Guide
- HubSpot
- Buffer 

for providing excellent style guide templates (here, here, and here), which we adapted and used in part in creating our style guide. 
- Wikipedia Style Guide
- HubSpot

## \- Buffer 

undefined
undefined
undefined
undefined
undefined
undefined

**Comment by VillageHubertChen** [comment] 2016-07-15 07:01
# Reproduced on second machine

We opened the above text in classeur on a second machine. Typing in that document tripped the same console error.

# Same document works in StackEdit

I opened the same document in StackEdit. No problem there. As such so far it appears not to be a problem of the markdown source file, nor an issue with my particular machine.

**Comment by benweet** [comment] 2016-07-15 07:34
Hi @VillageHubertChen 
Thank you very much for your effort. We can reproduce the issue.
We're investigating. We'll try to keep you informed in the next 24.

**Comment by benweet** [comment] 2016-07-15 23:54
Hi @VillageHubertChen 
Bug fixed in version v1.6.1 (deploying right now). It was caused by weird unicode separator characters in your file.
Thanks again for your help.

**Closed as completed by benweet** 2016-07-15 23:54 UTC

**Comment by VillageHubertChen** [comment] 2016-07-16 04:05
Dear Robert,

Thanks! I am on cloud 9. I can confirm that it works. We are using lots of unicode characters in our workflow. Thanks for making it working. Very appreciated!

We really love your app. We feel that user guides and tutorials will help others to recognize and unleash the power that Classeur has to offer. We are writing one right now. Let me know if you are interested and I will share the link to the article here, once it is ready.

On that note, do you have any links to Classeur Tutorials you can share with me? I do not want to reinvent the wheel. I just was not able to find them via google search.

**Comment by orschiro** [comment] 2016-07-18 06:17
Dear Hubert, 

> We are writing one right now. Let me know if you are interested and I will share the link to the article here, once it is ready.
> On that note, do you have any links to Classeur Tutorials you can share with me? I do not want to reinvent the wheel. I just was not able to find them via google search.

As already said by Ben, thank you very much for your effort to help us improve Classeur! 

Please do share your tutorial with us. 

We can create a new Section `Tutorials` on our help page [1].

Thankfully,

~Robert

[1] https://classeur.zendesk.com/hc/en-us

**Comment by VillageHubertChen** [comment] 2016-07-18 08:35
@benweet My apologies to confuse you with Robert! 

@benweet @orschiro 

Thanks for the reply. I will post the link here once the tutorial is done. It may take a bit, as it is part of a larger article series. 

You will be welcome to republish the article in your new tutorial section. All our writing is in CC-BY license, so all you have to do in the end to mention us with a link to the original article.

In any event we will promote classeur on our site wherever we can, hoping that we can bring you some more traffic.

~ Hubert

P.S. The core idea of our article series is to write and publish in kramdown (markdown) natively versus HTML centric traditional workflow. We already experienced and we demo in the article series as this has tremendous increase in efficiency. Classeur is one of the key applications used in this new, more productive workflow. Is this approach interesting for your business model? Making Classeur an essential tool on a more productive writing and publishing workflow?

**Comment by orschiro** [comment] 2016-07-20 06:56
Dear Hubert,

> Is this approach interesting for your business model? Making Classeur an essential tool on a more productive writing and publishing workflow?

It can certainly be. Thank you for all your efforts to promote Classeur. 

Looking forward to the article series. Based on this we can think of further promotional steps. 

Warmly,

~Robert

**Comment by VillageHubertChen** [comment] 2016-07-20 07:16
Dear Robert,

You are welcome. Here comes the → [Intro V²Flow.Publishing](https://v-squared.github.io/plan/flow/publishing/intro/) Article.

We are hoping to churn out one article per day.

You are welcome and invited to give feedback. The best way is for you to press the V²Flow button (The big orange circle with the pen). Then select "Article Issue". It opens the companion GitHub Issue. Next simply write a comment in that issue and you contributed your feedback and started your conversation with us on this Article.

We plan to give Classeur most of the space in the "Markdown Tools" Article.

We could give Classeur an even bigger role, if you were interested to make small changes that would have big impact to give the user a true WYSIWYG experience. But this maybe premature to discuss right now. 

To give you an idea where this could be going, please check out → [Appetizing Articles](https://v-squared.github.io/plan/flow/publishing/appetizing/). We are adding richly formatted tables, slide shows and rich table of contents in the markdown philosophy via kramdown, YML, Liquid, Jekyll, all of which are Open Source and I believe all of which are under MIT License.

I am very curious to get your take on this. If you like to chat on this with a little more immediate response or have a voice call, you can reach me on skype: hubertnchen . If you do contact me, write that you are Robert or from Classeur, as any neutral contact request will be deleted by me.

All the best,

~Hubert

**Comment by orschiro** [comment] 2016-07-23 06:12
Thank you Hubert!

This is an extensive amount of resources to digest. 

>  if you were interested to make small changes that would have big impact to give the user a true WYSIWYG experience

This is an interesting point. Mind sharing what you have in mind? 

We can see what we are able to integrate.

Thankfully,

~Robert

**Comment by VillageHubertChen** [comment] 2016-07-24 03:56
Dear Robert,

Thank you for your consideration. As per your request, here comes an example. I choose _Advanced Table Formatting_ as project that I hope qualifies as _Low Hanging Fruits_ for you. Meaning little work for you but big impact to your customers.

# Executive Summary

## Problem

There are five types of tabular data. They are represented via five table formatting styles. Markdown only provides one table formatting style. As such using markdown table to render tabular data of the other styles is misleading the reader and to many authors an enough limitation to consider that a markdown editor is just not mature enough to use in production yet.

## Solution

We have overcome this limitation, as you can see in the detailed example below.

## Your Business Opportunity

Include our solution to Classeur. With — what I believe would be relatively small changes — you could provide advanced table styling to Classeur including WYSIWG preview in your preview pane.

I believe this will expand your market to write production articles.

# Details

[Advanced Table Formatting](https://v-squared.github.io/plan/flow/publishing/appetizing/#advanced-table-formatting)

What the user gets is much more control on table styling, yet keep the simplicity of the markdown table workflow. This allows the user to choose one of five canned styles matching the five basic table data types:

| Table Style | Data Type |
| --: | :-- |
| Column Head | Standard table |
| Twin Head | Feature Comparison |
| Twin Head Description | Terms and Description |
| Row Head | Item Lists |
| No Head | List of Things |

You can make above table look like so:

![example-styled-table](https://cloud.githubusercontent.com/assets/7278716/17081653/49f07fec-5193-11e6-8f40-e29e78c17bd3.png)

The user would do this by adding one line of code in front of the table, which is a [kramdown Inline Attribute List](http://kramdown.gettalong.org/syntax.html#inline-attribute-lists) that looks like so:

{:.uk-table.twin-head.twin-blue}

To see how the five styles look like → [Reference for all Table Styles](https://v-squared.github.io/plan/flow/publishing/appetizing/#ref-table-styles)

We can provide styling and possibly more importantly documentation on how to use it. The documentation is actually ready, as you can see in the table section of → [Appetizing Articles](https://v-squared.github.io/plan/flow/publishing/appetizing/). We will be very cooperative to change features upon your requests.

# Going from here

## Talking might be more efficient

I need to make an awful lot of assumptions about you to write the above (I do not know you). If even one of my assumptions is wrong I might loose you. I am sure you have questions. The fastest way for you to get answers to your questions might be a skype call. You can reach me at: hubertnchen.

## There could be a sweeter low hanging fruits project

I also made assumptions what is easy for you to implement. I might be off there as well. There are many possible low hanging fruits projects other than advanced table formatting. I suggest in a brainstorming we pick one most easy for you to implement. We then create a small but successful project working together and go from there.

**Comment by orschiro** [comment] 2016-07-25 09:14
Dear Hubert, 

I see the direction you're coming from. Thank you! 

> Include our solution to Classeur. With — what I believe would be relatively small changes — you could provide advanced table styling to Classeur including WYSIWG preview in your preview pane.

How can we return value back to you? Do you expect payments from our side? 

I am not sure whether and to what extent the advanced table formatting could be implemented into Classeur. That's about to @benweet to evaluate. 

However, in principle I can clearly see how advanced table formatting could benefit the users, especially from the academic front. 

~Robert

**Comment by VillageHubertChen** [comment] 2016-07-26 04:26
Dear Robert,

Thank you for your review and your further questions. See my answers below:

## Return Value vs. Synergies

I am expecting no payment. I am also not expecting that I need to pay you for your changes. Instead I am proposing a synergy for both teams:
1. **Your Benefits:** Changes I propose move your App forward in that you can reach your marketing goals faster.
   1. Do you have a documenting outlining as to where Classeur is going?
2. **Our Benefits:** By you fixing bugs or adding features our team can work faster, as Classeur works better for us.

## Value of Advanced Tables

We are using advanced tables in:
1. Product Pages
2. Brochures
3. White Paper
4. Workflow Instructions

We recognize (and I hope you will agree) that advanced table formatting is a useful feature for a much wider field than academics alone. The market size you will be appealing with it might be greater than you think, including commercial users, such as run of the mill companies.

## Simpler Low Hanging Fruit Project

I will keep on the look out for a simpler project which has more immediate return for you and involves less effort for you.

~Hubert
