### ISSUE TITLE
Bug in editor with keyboard text selection

### ISSUE THREAD

**Issue by sheljohn** [classeur/classeur#128] opened 2016-06-16 14:03 UTC
I think this is a bug, but this might be an obscure mis-feature. Here is an MVCE:
1. Type a sentence with several words.
2. Put the cursor somewhere towards the start, then either use `Ctrl+Shift+Right` (on Linux) or `Alt+Shift+Right` (on Mac) to select text word-by-word towards the end of the sentence. Select a few words like this.
3. Now while the text is selected, type `Shift+Left` (on both Linux and Mac).

The expected behaviour (with every text editor I've used) is that you should unselect character-by-character from the **right**. But instead it seems to select additional characters from the left.

On a related note, a "feature" which I originally thought was nice, but which might actually be a related bug, is that if I use `Cmd+Shift+Right` (on Mac) to select until the end of the line, and then `Cmd+Shift+Left`, I would expect the cursor to go back to where it was and unselect all the text on the line, but instead it selects the entire line until the beginning on the left.

---

**Edit:** Actually it is definitely a bug because if you select word-by-word towards the left, and then character-by-character towards the right, it does yield the expected behaviour of unselecting from the left instead of selecting more on the right.

**Comment by orschiro** [comment] 2016-06-16 15:12
Dear @Sheljohn,

Thanks for your report but I can't reproduce your bug.

![output](https://cloud.githubusercontent.com/assets/170947/16121930/70c78d5c-33e5-11e6-88c3-9868a89b9e31.gif)

**Comment by sheljohn** [comment] 2016-06-16 20:48
@orschiro Thanks for your comment, actually I just tested on Linux and it works fine. Intriguing. I will restart my Mac and test again.

**Comment by orschiro** [comment] 2016-06-17 05:51
@Sheljohn, glad it seems to be not a bug. :smiley: 

Thanks for your response!

~Robert

**Comment by sheljohn** [comment] 2016-06-17 07:14
@orschiro It is still a bug on Mac with Chrome, even after restarting...

Could it be an error because of the different key-bindings on Mac?

**Comment by orschiro** [comment] 2016-06-17 07:16
I am sorry that I have closed it too quickly!

Can someone else on a Mac and Chrome please try to reproduce this?

**Comment by sheljohn** [comment] 2016-06-17 07:35
Here is an short screencast: https://youtu.be/8sCoLw0iqgQ

**Comment by benweet** [comment] 2016-06-27 20:47
Yeah I can reproduce this.

**Comment by benweet** [comment] 2016-06-28 23:08
Should be fixed in v1.5.

**Closed as completed by benweet** 2016-06-28 23:08 UTC
Labels: bug
