### ISSUE TITLE
How to enable code syntax highlighting

### ISSUE THREAD

**Issue by djbhsys** [classeur/classeur#142] opened 2016-07-21 06:45 UTC
I'm working on a doc of the tool i built,and this doc include some **Lua** code.I used to write it on StackEdit.io,and i trying this new tools now,but it seems code syntax highlighting is not working fine.Do classeur support code syntax highlighting?If it did how to use it and which language are support by it?

**Comment by orschiro** [comment] 2016-07-22 14:36
Dear @djbhsys,

Does this article help you solve the problem?

https://classeur.zendesk.com/hc/en-us/articles/209336029

Thankfully,

~Robert

**Comment by djbhsys** [comment] 2016-07-23 06:48
@orschiro Thanks for your reply :)
![image](https://cloud.githubusercontent.com/assets/3361871/17076440/30deb28a-50e4-11e6-943b-b42d83891dda.png)

Not Work,although js is work fine,it's just not support lua or this is some sort of bug?

**Comment by orschiro** [comment] 2016-07-23 07:11
You're welcome. :-)

You mean, with lua, you are missing colours?

In that case, I can reproduce the problem. 

@benweet do we need to address this issue upstream at Prism?

**Comment by benweet** [comment] 2016-07-23 08:59
Need to investigate first.

**Comment by benweet** [comment] 2016-07-25 16:24
Looks like the version of prism.js we have is a bit old. We need to upgrade to have lua and other languages support.

**Comment by djbhsys** [comment] 2016-08-04 09:53
Do you have a schedule to fix this issue?I hope I can use Classeur as my main edit tool earlier :)

**Comment by benweet** [comment] 2016-08-04 09:56
Already fixed in v1.7.0. Try this:

``````
```lua
print("Hello World!")
```
``````

**Closed as completed by benweet** 2016-08-04 09:56 UTC
Labels: question
