### ISSUE TITLE
Strong test does not support Chinese！

### ISSUE THREAD

**Issue by hgfgood** [classeur/classeur#104] opened 2016-03-20 10:08 UTC
I use Chinese in my document, but i fond it does not fit well.

Thanks a lot, Plese fix it. I like classesur very much!
Guangfu He

**Comment by benweet** [comment] 2016-04-30 16:00
Hi, can you provide a sample document to reproduce the issue?
thanks

**Comment by hgfgood** [comment] 2016-05-02 03:16
1. cannot print out in view window on time, some times need a `space`(` `) to trigger flush and  print out normally.
   examples:
   ![Uploading 20160502110822.png…](http://119.29.134.184/wp-content/uploads/2016/05/problem1.png)
   ![Uploading 20160502110847.png…](http://119.29.134.184/wp-content/uploads/2016/05/problem2.png)
   and after trigger the print, I can delete the`space`(` `)

you can also see, the Chinese does not print out boldly format as English(Both in header and `** **`)

**Comment by benweet** [comment] 2016-06-22 10:07
This is because of the space before the closing `**`, it's not linked to the use of chinese character.

EDIT: Indeed the chinese characters doesn't look bold. It may be related to this issue: https://github.com/classeur/classeur/issues/70

**Closed as completed by benweet** 2016-06-22 10:07 UTC
